from setuptools import setup, find_packages

setup(
    name="seba",
    version="0.1.0",
    description="روبوت خبير الأسهم للتحليل - نظام تحليل أسهم مدعوم بالذكاء الاصطناعي يطبق منهجية SEPA",
    author="SEBA Team",
    author_email="info@seba.com",
    packages=find_packages(),
    install_requires=[
        "pandas>=2.0.0",
        "numpy>=1.24.3",
        "yfinance>=0.2.18",
        "alpha_vantage>=2.3.1",
        "requests>=2.28.2",
        "beautifulsoup4>=4.12.0",
        "aiohttp>=3.8.4",
        "psycopg2-binary>=2.9.6",
        "sqlalchemy>=2.0.9",
        "redis>=4.5.4",
        "alembic>=1.10.3",
        "scikit-learn>=1.2.2",
        "matplotlib>=3.7.1",
        "seaborn>=0.12.2",
        "plotly>=5.14.1",
        "openai>=0.27.4",
        "tiktoken>=0.3.3",
        "transformers>=4.28.1",
        "fastapi>=0.95.1",
        "uvicorn>=0.21.1",
        "pydantic>=1.10.7",
        "python-dotenv>=1.0.0",
        "python-jose>=3.3.0",
        "passlib>=1.7.4",
        "python-multipart>=0.0.6",
    ],
    python_requires=">=3.10",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Financial and Insurance Industry",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
    ],
)
